name: Packer Validation

on:
  pull_request:
    branches:
     - main
jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: '1.8.6'

      - name: Initialize Packer
        run: packer init .
       
      - name: Packer fmt
        run: packer fmt -check aws-debian.pkr.hcl

      - name: Run `Build the webapp artifact`
        run: |
          packer fmt -check aws-debian.pkr.hcl

      - name: Packer validate
        run: |
          packer validate aws-debian.pkr.hcl
          
      - name: Check for errors
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Packer template formatting and validation succeeded."
          else
            echo "Packer template formatting or validation failed."
            exit 1
          fi

      - name: Fail if Packer validation fails
        if: ${{ failure() }}
        run: |
          echo "Packer validation failed. Preventing pull request from merging."
          exit 1
